//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Settings/Input/InputCollection.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace ChaosMission.Input
{
    public partial class @InputCollection : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputCollection()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputCollection"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""cec8b14f-6e9b-4aea-8001-8faf46d13359"",
            ""actions"": [
                {
                    ""name"": ""Moving"",
                    ""type"": ""Value"",
                    ""id"": ""9c4b376f-2b00-4a2c-8c24-5ed2694609f1"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shooting"",
                    ""type"": ""Button"",
                    ""id"": ""d031ab5e-46b9-4e9b-ae74-5e2d1b354986"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jumping"",
                    ""type"": ""Button"",
                    ""id"": ""b0470950-05a3-4cb6-820e-c44802b77cf6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClimbingDownhill"",
                    ""type"": ""Button"",
                    ""id"": ""1d34af8f-ff1c-4b12-8e14-c5db99a750fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClimbingJump"",
                    ""type"": ""Button"",
                    ""id"": ""8089b770-c131-4c05-a9fb-795d06c48aa1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Laddering"",
                    ""type"": ""Value"",
                    ""id"": ""e69baba7-a65f-461a-bff0-bfafcf962695"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2e6d3588-340c-4091-b093-42c8f8a0fce4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Shooting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e32aa39-e423-4aa5-b2a8-30e2c30370fa"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Jumping"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b50c3473-51d6-4d16-a8dd-12a19b0aefc0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""ClimbingDownhill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a89972db-fb18-4927-881d-2f2c09ed90b5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""ClimbingJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""9644f0ec-12e0-49d1-aef4-ab2d86ef79e2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""b6490bed-cf14-4234-a490-f2941b478bf7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""4d8540d3-b9f6-45c5-b373-5a60b9192aaa"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a65582c8-e828-4aaf-9ca8-e7374c40daaa"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Laddering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6f63fd10-da21-436b-a9ad-70ea77557d07"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Laddering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5b433fe2-f862-4f62-96c1-e6161b4e19d1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Laddering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""64ae8d2e-f3a0-4e28-b214-616486fe6040"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Laddering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a88f6401-b01c-4d7f-b535-3ffde01b12ca"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Laddering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""MouseKeyboard"",
            ""bindingGroup"": ""MouseKeyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Moving = m_Player.FindAction("Moving", throwIfNotFound: true);
            m_Player_Shooting = m_Player.FindAction("Shooting", throwIfNotFound: true);
            m_Player_Jumping = m_Player.FindAction("Jumping", throwIfNotFound: true);
            m_Player_ClimbingDownhill = m_Player.FindAction("ClimbingDownhill", throwIfNotFound: true);
            m_Player_ClimbingJump = m_Player.FindAction("ClimbingJump", throwIfNotFound: true);
            m_Player_Laddering = m_Player.FindAction("Laddering", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private IPlayerActions m_PlayerActionsCallbackInterface;
        private readonly InputAction m_Player_Moving;
        private readonly InputAction m_Player_Shooting;
        private readonly InputAction m_Player_Jumping;
        private readonly InputAction m_Player_ClimbingDownhill;
        private readonly InputAction m_Player_ClimbingJump;
        private readonly InputAction m_Player_Laddering;
        public struct PlayerActions
        {
            private @InputCollection m_Wrapper;
            public PlayerActions(@InputCollection wrapper) { m_Wrapper = wrapper; }
            public InputAction @Moving => m_Wrapper.m_Player_Moving;
            public InputAction @Shooting => m_Wrapper.m_Player_Shooting;
            public InputAction @Jumping => m_Wrapper.m_Player_Jumping;
            public InputAction @ClimbingDownhill => m_Wrapper.m_Player_ClimbingDownhill;
            public InputAction @ClimbingJump => m_Wrapper.m_Player_ClimbingJump;
            public InputAction @Laddering => m_Wrapper.m_Player_Laddering;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
                {
                    @Moving.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoving;
                    @Moving.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoving;
                    @Moving.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoving;
                    @Shooting.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShooting;
                    @Shooting.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShooting;
                    @Shooting.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShooting;
                    @Jumping.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJumping;
                    @Jumping.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJumping;
                    @Jumping.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJumping;
                    @ClimbingDownhill.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClimbingDownhill;
                    @ClimbingDownhill.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClimbingDownhill;
                    @ClimbingDownhill.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClimbingDownhill;
                    @ClimbingJump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClimbingJump;
                    @ClimbingJump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClimbingJump;
                    @ClimbingJump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClimbingJump;
                    @Laddering.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLaddering;
                    @Laddering.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLaddering;
                    @Laddering.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLaddering;
                }
                m_Wrapper.m_PlayerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Moving.started += instance.OnMoving;
                    @Moving.performed += instance.OnMoving;
                    @Moving.canceled += instance.OnMoving;
                    @Shooting.started += instance.OnShooting;
                    @Shooting.performed += instance.OnShooting;
                    @Shooting.canceled += instance.OnShooting;
                    @Jumping.started += instance.OnJumping;
                    @Jumping.performed += instance.OnJumping;
                    @Jumping.canceled += instance.OnJumping;
                    @ClimbingDownhill.started += instance.OnClimbingDownhill;
                    @ClimbingDownhill.performed += instance.OnClimbingDownhill;
                    @ClimbingDownhill.canceled += instance.OnClimbingDownhill;
                    @ClimbingJump.started += instance.OnClimbingJump;
                    @ClimbingJump.performed += instance.OnClimbingJump;
                    @ClimbingJump.canceled += instance.OnClimbingJump;
                    @Laddering.started += instance.OnLaddering;
                    @Laddering.performed += instance.OnLaddering;
                    @Laddering.canceled += instance.OnLaddering;
                }
            }
        }
        public PlayerActions @Player => new PlayerActions(this);
        private int m_MouseKeyboardSchemeIndex = -1;
        public InputControlScheme MouseKeyboardScheme
        {
            get
            {
                if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("MouseKeyboard");
                return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        public interface IPlayerActions
        {
            void OnMoving(InputAction.CallbackContext context);
            void OnShooting(InputAction.CallbackContext context);
            void OnJumping(InputAction.CallbackContext context);
            void OnClimbingDownhill(InputAction.CallbackContext context);
            void OnClimbingJump(InputAction.CallbackContext context);
            void OnLaddering(InputAction.CallbackContext context);
        }
    }
}
